"""
AI Insight Generation + PDF Export
Génère une mini-analyse du marché israélien via OpenAI
Exporte en PDF avec branding IGV
"""
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, EmailStr
from typing import Optional
import os
import openai
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.pdfgen import canvas
from io import BytesIO
from datetime import datetime
import base64
import logging

router = APIRouter(prefix='/api/ai', tags=['AI Insights'])

# OpenAI API Key
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
if OPENAI_API_KEY:
    openai.api_key = OPENAI_API_KEY
else:
    logging.warning("OPENAI_API_KEY not configured")


class InsightRequest(BaseModel):
    email: EmailStr
    sector: str
    companyAge: Optional[str] = None
    differentiation: str


class InsightResponse(BaseModel):
    analysis: str
    pdfUrl: str


def generate_ai_insight(sector: str, company_age: Optional[str], differentiation: str) -> str:
    """
    Génère une mini-analyse via OpenAI GPT-4
    20-30 lignes, ton professionnel, non commercial
    """
    if not OPENAI_API_KEY:
        raise HTTPException(status_code=503, detail="AI service not configured")
    
    prompt = f"""You are a market analysis expert specialized in the Israeli market.

Generate a preliminary Israel market insight (20-30 lines) for a company with the following characteristics:

**Sector:** {sector}
**Company age:** {company_age or 'Not specified'}
**Unique differentiation:** {differentiation}

Your analysis should be:
- Professional and factual (not promotional)
- Specific to the Israeli market context
- Cover: market relevance, potential challenges, cultural considerations, first steps
- Mention competitive landscape if relevant
- Be honest about potential difficulties
- Provide actionable initial orientation

Format the response as plain text paragraphs, professional tone, approximately 20-30 lines.

DO NOT include:
- Direct sales pitch
- Pricing information
- "Contact us" calls to action (will be added separately)
- Overly optimistic promises

The analysis should help the reader understand if Israel could be a viable market for their business."""

    try:
        response = openai.chat.completions.create(
            model="gpt-4-turbo-preview",
            messages=[
                {"role": "system", "content": "You are a professional market analyst specialized in the Israeli market. Provide factual, balanced insights."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.7,
            max_tokens=1500
        )
        
        analysis = response.choices[0].message.content.strip()
        
        # Ajouter le paragraphe obligatoire de fin
        disclaimer = "\n\nThis first insight was generated by an AI model based on your inputs. It provides an initial orientation but does not replace a full human market analysis. If you want a detailed, strategic and location-based study, you can request a complete analysis conducted by Israel Growth Venture."
        
        return analysis + disclaimer
        
    except Exception as e:
        logging.error(f"OpenAI API error: {str(e)}")
        raise HTTPException(status_code=500, detail="Failed to generate insight")


def generate_pdf(email: str, sector: str, analysis: str) -> str:
    """
    Génère un PDF avec branding IGV
    Retourne une URL base64 data URL pour téléchargement direct
    """
    buffer = BytesIO()
    
    # Create PDF
    doc = SimpleDocTemplate(buffer, pagesize=A4,
                           rightMargin=0.75*inch, leftMargin=0.75*inch,
                           topMargin=0.75*inch, bottomMargin=0.75*inch)
    
    story = []
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor='#1e40af',
        spaceAfter=12,
        alignment=TA_CENTER
    )
    
    subtitle_style = ParagraphStyle(
        'CustomSubtitle',
        parent=styles['Normal'],
        fontSize=12,
        textColor='#6b7280',
        spaceAfter=20,
        alignment=TA_CENTER
    )
    
    hebrew_style = ParagraphStyle(
        'Hebrew',
        parent=styles['Normal'],
        fontSize=10,
        textColor='#6b7280',
        spaceAfter=20,
        alignment=TA_CENTER
    )
    
    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['Normal'],
        fontSize=11,
        leading=16,
        spaceAfter=12,
        alignment=TA_LEFT
    )
    
    footer_style = ParagraphStyle(
        'Footer',
        parent=styles['Normal'],
        fontSize=9,
        textColor='#9ca3af',
        alignment=TA_CENTER
    )
    
    # Header avec branding
    story.append(Paragraph("Israel Growth Venture", title_style))
    story.append(Paragraph("ייעוץ בנושא התרחבות ופיתוח פעילות בישראל", hebrew_style))
    story.append(Spacer(1, 0.3*inch))
    
    story.append(Paragraph("AI-Generated Preliminary Market Insight", subtitle_style))
    story.append(Spacer(1, 0.2*inch))
    
    # Metadata
    story.append(Paragraph(f"<b>Sector:</b> {sector}", body_style))
    story.append(Paragraph(f"<b>Generated for:</b> {email}", body_style))
    story.append(Paragraph(f"<b>Date:</b> {datetime.now().strftime('%B %d, %Y')}", body_style))
    story.append(Spacer(1, 0.3*inch))
    
    # Analysis content
    story.append(Paragraph("<b>Your Israel Market Insight:</b>", styles['Heading2']))
    story.append(Spacer(1, 0.1*inch))
    
    # Split analysis into paragraphs
    paragraphs = analysis.split('\n\n')
    for para in paragraphs:
        if para.strip():
            story.append(Paragraph(para.strip(), body_style))
            story.append(Spacer(1, 0.1*inch))
    
    # Footer
    story.append(Spacer(1, 0.5*inch))
    story.append(Paragraph("© Israel Growth Venture", footer_style))
    story.append(Paragraph("israelgrowthventure.com", footer_style))
    
    # Build PDF
    doc.build(story)
    
    # Get PDF bytes
    pdf_bytes = buffer.getvalue()
    buffer.close()
    
    # Convert to base64 data URL
    pdf_base64 = base64.b64encode(pdf_bytes).decode('utf-8')
    data_url = f"data:application/pdf;base64,{pdf_base64}"
    
    return data_url


@router.post('/generate-insight', response_model=InsightResponse)
async def generate_insight(request: InsightRequest):
    """
    Génère une mini-analyse IA + PDF téléchargeable
    """
    try:
        # Generate AI analysis
        analysis = generate_ai_insight(
            sector=request.sector,
            company_age=request.companyAge,
            differentiation=request.differentiation
        )
        
        # Generate PDF
        pdf_url = generate_pdf(
            email=request.email,
            sector=request.sector,
            analysis=analysis
        )
        
        # Log pour analytics (sans données sensibles)
        logging.info(f"AI Insight generated - Sector: {request.sector}")
        
        return InsightResponse(
            analysis=analysis,
            pdfUrl=pdf_url
        )
        
    except HTTPException:
        raise
    except Exception as e:
        logging.error(f"Insight generation error: {str(e)}")
        raise HTTPException(status_code=500, detail="Failed to generate insight")
